name: Extract openapi definition
'on': push
jobs:
  update_openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: 18.11.0
      - run: npm ci
      - run: node openapi/openapi.mjs
      - run: npx @redocly/cli lint openapi/openapi.json
      - uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: openapi/openapi.json
          title: update openapi definition
          branch: openapi
          commit-message: 'chore(openapi): update openapi definition'
      - run: mkdir -p build
      - run: >-
          npx api2html -o build/index.html -l shell,javascript
          openapi/openapi.json
      - uses: actions/upload-artifact@v3
        with:
          name: openapi
          path: ${{ github.workspace }}/build/**/*
          retention-days: 2
      - uses: blake-mealey/openapi-review-action@v1
        with:
          spec-paths: openapi/openapi.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
  publish_doc:
    needs:
      - update_openapi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: konsumation/konsumation.github.io
      - uses: actions/download-artifact@v3
        with:
          name: openapi
          path: openapi
      - name: Deploy Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          external_repository: konsumation/konsumation.github.io
          publish_branch: master
          publish_dir: openapi
          destination_dir: openapi
          enable_jekyll: true
